server:
  port: 8081

spring:
  application:
    name: spring-security-keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8080/realms/my-app}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8080/realms/my-app}/protocol/openid-connect/certs

app:
  security:
    jwt:
      issuer-validate-uri: ${JWT_ISSUER_VALIDATE_URI:http://localhost:8080/realms/my-app}
    cors:
      allowed-origins:
        - ${CORS_ALLOWED_ORIGINS:http://localhost:3000}